name: Personal Wiki Stack - Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image of your personal wiki 
      run: docker build . --file docker-compose-init --tag personal-wiki-start:$(date +%s)
